### ISSUE TITLE
How'd you reverse-engineer this?

### ISSUE THREAD

**Issue by tejasmanohar** [aurbano/robinhood-node#13]
Interested in hearing what process you took to develop this. Did you setup a MITM proxy from your mobile device and look at request data? What tool(s) did you find handy (like Charles?)? Any tips for those trying to reverse-engineer Robinhood API / send more PRs to help this one on setting up MITM proxy or whichever route you took (i.e. anything you had to do to get around the SSL pinning etc) :)

**Comment by aurbano** [comment]
All you need is a proxy setup on the phone, and then a mitm server running on your laptop. 

This one is pretty good: https://mitmproxy.org/

If you'd rather use something with an interface try https://portswigger.net/burp/

SSL pinning might give you issues, it wasn't a problem when I tried but I'm pretty sure you can find workarounds. Since you control the phone and the mitm server it should be fairly easy to create valid SSL certificates.

**Comment by tejasmanohar** [comment]
Aha thanks
