### ISSUE TITLE
Automatically apply `.toUpper()` anywhere passing in a stock/symbol

### ISSUE THREAD

**Issue by nodesocket** [aurbano/robinhood-node#18]
Seems like the `stock` parameter in `quote_data()` is case-sensitive which it **should not be**.

```shell
➜  node quotes --stock AAPL
{ results:
   [ { ask_price: '96.9100',
       ask_size: 4100,
       bid_price: '96.9000',
       bid_size: 400,
       last_trade_price: '96.9100',
       last_extended_hours_trade_price: '96.8900',
       previous_close: '96.7600',
       adjusted_previous_close: '96.7600',
       previous_close_date: '2016-02-25',
       symbol: 'AAPL',
       trading_halted: false,
       updated_at: '2016-02-26T21:00:00Z' } ] }

StatusCode: 200
```

```shell
➜  node quotes --stock aapl
undefined

StatusCode: 400
```

Anybody else think we should automatically apply `.toUpper()` anywhere in this package we are passing in a stock/symbol?

**Comment by aurbano** [comment]
@nodesocket good catch, yes that would be a great idea.

My plan was to add in models for each piece of data, and then we'll have them maintain data integrity.

But for now calling `.toUpperCase()` on the symbol field automatically would be a good solution. Feel free to send a PR referencing this issue if you want, I'll do the change otherwise.
