### ISSUE TITLE
How to authenticate

### ISSUE THREAD

**Issue by rohitramkumar** [aurbano/robinhood-node#22]
I am having trouble authenticating a user. I have tried the following but the API is rejecting it:

Robinhood({username:'myusername', password:'mypassword'});

Any idea what I am doing wrong?

**Comment by annieechen** [comment]
How did you end up figuring this out?

**Comment by aurbano** [comment]
@annieechen I suppose there was something else wrong with this approach, since the code should work fine. The credentials must be passed on initialisation, and the library will do the login straight away:

```js
var robinhood = Robinhood({username:'myusername', password:'mypassword'});

// it should now be authenticated
```

I'm planning on rewriting this slightly to use promises instead of callbacks, since at the moment there isn't unfortunately a way to know for sure that the login has already been completed. So maybe his issue was that the login hadn't finished by the time he was sending requests.
