### ISSUE TITLE
updated_at at the millisecond 

### ISSUE THREAD

**Issue by jgozal** [aurbano/robinhood-node#32]
Since prices for securities can change within the same second, is there any way to get the updated_at string at the millisecond?

I am getting price changes within the same updated_at time.

jg

**Comment by jspenc72** [comment]
If you are looking at high frequency trading I use new Date() if in memory or immediately write the prices to Cassandra and use the timestamp generated by cassandra. This way you are not relying on updated_at which seems to change based on which robinhood server gives a response... 
This works because from the point of view of your app the time difference between the local clock and updated_at is comparable to flight time of the request.

**Comment by jspenc72** [comment]
@DevKiddo 

This library allows you to get millisecond updates. Check out the observable example shown in the usage.

https://github.com/jspenc72/robinhood-observer
https://www.npmjs.com/package/robinhood-observer
